### ISSUE TITLE
add_function parameters are strings and not arrays

### ISSUE THREAD

**Issue by epareja2** [unconv/php-gpt-funcs#3]
Hello, thank you for this library and I'm new to this ChatGPT API.
I'm trying to create a class for defining funtions like this

class myFunctionsClass {
  protected ChatGPT $chatGPT;  // This is your class
 
 /**
 * This function do something very cool
 *  @param  $test : string having the result from chatgpt
 */
  public function doSomething(string $test) {
     // do something with $test
  }
}

In that same class I'm defining a constructor to add the defined functions like this

 public function __construct()
    {
        $api_key = env('OPENAI_API_KEY');
        $this->chatGPT = new ChatGPT($api_key);
        $this->chatGPT->add_function('doSomething');
    }

The line that assigns a function throws an error

App\Libraries\ChatGPT::add_function(): Argument #1 ($function) must be of type callable|array, string given,

What am I doing wrong here?

Thank you and hopefully you can check this.

Regards

Ernesto Pareja

**Comment by unconv** [comment]
Hi! In PHP, you can pass a class method as a `callable` by creating an array with the first element being the object and the second element being the method to call. So in this case you need to pass the function as `[$this, 'doSomething']` to `add_function`.

```php
$this->chatGPT->add_function( [$this, 'doSomething'] );
```

However, I didn't take this into account in designing the library, so it didn't work either. I have now updated the library to work with classes as well. You can find an example of this in `examples/class_example.php`

Note that the method needs to be public so that the ChatGPT library class can call it.

**Comment by epareja2** [comment]
Thank you!!! That worked perfectly!
